import { AudioFeatures, Page, PlaylistedTrack, SimplifiedPlaylist, SpotifyApi, Track } from '@spotify/web-api-ts-sdk';
import { FC, useCallback, useEffect, useState } from 'react';
import PlaylistCardComponent from '../PlaylistCardComponent/PlaylistCardComponent';
import { Button, Col, FloatingLabel, Form, InputGroup, Row } from 'react-bootstrap';
import moment from 'moment';
import { DataSet } from '../../types/DataSet';
import GraphComponent from '../GraphComponent/GraphComponent';
import { createPlaylistFromCurve } from '../../utils/playlistGenerator';

type Props = {
  sdk: SpotifyApi;
  dataState: DataSet;
  durationMs: number;
};

type Status = {
  state: 'idle' | 'loading' | 'error' | 'success';
  data: any;
};

const PlaylistSelectionComponent: FC<Props> = ({ sdk, dataState, durationMs }) => {
  const [results, setResults] = useState<Page<SimplifiedPlaylist> | null>(null);
  const [selectedPlaylist, setSelectedPlaylist] = useState<SimplifiedPlaylist | null>(null);
  const [tracks, setTracks] = useState<(PlaylistedTrack<Track> & AudioFeatures)[] | null>(null);
  const [browseTracks, setBrowseTracks] = useState<boolean>(false);
  const [playlistName, setPlaylistName] = useState<string>('');
  const [status, setStatus] = useState<Status>({ state: 'idle', data: null });
  const [generatedPlaylist, setGeneratedPlaylist] = useState<{
    dataState: DataSet;
    durationMs: number;
    bpmSteps: number;
    progressSteps: number;
    additionalData?: [number, any][];
  } | null>(null);

  useEffect(() => {
    (async () => {
      const results = await sdk.currentUser.playlists.playlists();
      setResults(() => results);
    })();
  }, [sdk]);

  useEffect(() => {
    (async () => {
      if (selectedPlaylist && selectedPlaylist.tracks && selectedPlaylist.tracks.total > 0 && tracks === null) {
        const tracks: (PlaylistedTrack<Track> & AudioFeatures)[] = [];
        const steps = 50;
        const total = selectedPlaylist.tracks.total;
        const pages = Math.ceil(total / steps);
        for (let i = 0; i < pages; i++) {
          const page = await sdk.playlists.getPlaylistItems(
            selectedPlaylist.id,
            undefined,
            'items(track(id, name, duration_ms, track_number, uri))',
            steps,
            i * steps
          );
          const detailedTracks = await sdk.tracks.audioFeatures(page.items.map((item) => item.track.id));
          const combinedTracks = page.items.map((item, index) => ({
            ...item,
            ...detailedTracks[index],
          }));
          tracks.push(...combinedTracks);
        }
        setTracks(() => tracks);
      } else {
        setTracks(null);
      }
    })();
  }, [selectedPlaylist, sdk]);

  const getPlaylistDuration = () => {
    if (tracks) {
      return moment.utc(tracks.reduce((acc, track) => acc + track.track.duration_ms, 0)).format('HH:mm:ss');
    }
    return '';
  };

  const generatePlaylist = useCallback(async () => {
    if (selectedPlaylist && tracks && dataState && durationMs) {
      const { newPlaylist, newDataState, additionalData } = createPlaylistFromCurve(tracks, dataState, durationMs);
      setGeneratedPlaylist({
        dataState: newDataState,
        durationMs: newPlaylist.reduce((acc, track) => acc + track.track.duration_ms, 0),
        bpmSteps: 5,
        progressSteps: 5,
        additionalData,
      });

      const currentUser = await sdk.currentUser.profile();
      const playlist = await sdk.playlists.createPlaylist(currentUser.id, {
        name: playlistName,
        description: 'Generated by the Spotify DJ',
        public: false,
      });
      await sdk.playlists.addItemsToPlaylist(
        playlist.id,
        newPlaylist.map((track) => track.track.uri),
        undefined
      );
      setStatus({ state: 'success', data: newPlaylist });
    } else {
      console.error('No playlist selected or no tracks found', selectedPlaylist, tracks, dataState, durationMs);
    }
  }, [selectedPlaylist, tracks, dataState, durationMs, playlistName, sdk]);

  return (
    <>
      <h1>Spotify Search for The Beatles</h1>
      {selectedPlaylist && tracks ? (
        <>
          <Row>
            <Col xs={8}>
              <h2>
                <span className="bi-backspace clickable" onClick={() => setSelectedPlaylist(null)}></span>{' '}
                {selectedPlaylist.name} - {tracks.length} tracks - {getPlaylistDuration()}
              </h2>
            </Col>
            <Col xs={4} className="d-flex justify-content-end">
              <Button onClick={() => setBrowseTracks((prev) => !prev)}>Browse Tracks</Button>
            </Col>
          </Row>
          {/* Track Browser */}
          {browseTracks &&
            (tracks.length > 0 ? (
              tracks.map((track, i) => (
                <div key={track.track.id}>
                  <p>
                    {i + 1}. {track.track.name} - {moment.utc(track.track.duration_ms).format('mm:ss')} - {track.tempo}{' '}
                    BPM
                  </p>
                </div>
              ))
            ) : (
              <p>No tracks found</p>
            ))}
          <Row>
            <InputGroup>
              <FloatingLabel controlId="floatingInput" label="Playlist name">
                <Form.Control
                  min={1}
                  type="text"
                  placeholder="Playlist name"
                  aria-label="Playlist name"
                  aria-describedby="basic-addon2"
                  onFocus={(e) => {
                    e.currentTarget.select();
                  }}
                  onInput={(e) => {
                    setPlaylistName(e.currentTarget.value);
                  }}
                />
              </FloatingLabel>
              <Button disabled={!playlistName || playlistName.length < 1} onClick={generatePlaylist}>
                Generate Playlist
              </Button>
            </InputGroup>
            {generatedPlaylist && (
              <Col xs={9} style={{ maxHeight: '50vh' }}>
                <GraphComponent
                  dataState={generatedPlaylist.dataState}
                  bpmSteps={generatedPlaylist.bpmSteps}
                  progressSteps={generatedPlaylist.progressSteps}
                  durationMs={generatedPlaylist.durationMs}
                  setData={() => {}}
                  additionalData={generatedPlaylist.additionalData}
                />
              </Col>
            )}

             {status.state === 'success' && (
              <p>
                Playlist created: {status.data.name} -{' '}
                <a
                  onClick={() => {
                    window.open(status.data.external_urls.spotify, '_blank');
                  }}
                >
                  {status.data.external_urls.spotify}
                </a>
              </p>
            )}
          </Row>
        </>
      ) : (
        <Row>
          {results?.items.map((playlist) => (
            <Col key={playlist.id} xs={2} className="mb-3 aspectSquare">
              <PlaylistCardComponent key={playlist.id} playlist={playlist} setSelectedPlaylist={setSelectedPlaylist} />
            </Col>
          ))}
        </Row>
      )}
    </>
  );
};

export default PlaylistSelectionComponent;
